name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
    use-axios:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: apt install
            - name: Use Axios
              uses: actions/github-script@v7
              with:
                script: |
                  const axios = require('axios'):
                  const res = await axios('https://icanhazdadjoke.com/', { headers: {
                    Accepts: 'text/plain' }})
                  console.log(res.data)