name: Docker
on:
    [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
            # credentials:
            #     username:
            #     password:
            env:
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
            #     - vol_name:/caminho/no/container
            #     - /caminho/anonimo/no/container
            #     - caminho/no/host:/caminho/no/container
            # options: --cpus 1
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Var
              run: echo $API_URL
            - name: Create a file
              run: echo 'Vitorino E' > text.txt
            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2+9
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: Show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt
            - uses: actions/checkout@v4
            - name: Run a bash script
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: ./script.sh
                args: "Some string"