name: Matrix
on: [push]

jobs:
    node-matrix:
        continue-on-error: ${{ matrix.experimental == true }}
        strategy:
            matrix:
                os: [ubuntu-latest, windowns-latest]
                node-version: [14, 16, 18]
                include:
                    - os: ubuntu-latest
                      is-ubuntu: true
                    - os: macos-latest
                      node-version: 15
                    - experimental: false
                    - os: ubuntu-latest
                      node-version: 18
                      experimental: true
                exclude:
                    - os: ubuntu-latest
                      node-version: 14
            fail-fast: true
            # max-parallel: 2
        runs-on: ${{ matrix.os }}
        steps:
            - if: matrix.experimental == true
              run: exit 1
            - run: node -v
            - run: echo '${{ toJson(matrix) }}'
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v