name: Matrix
on: [push]

jobs:
    node-matrix:
        strategy:
            matrix:
                os: [ubuntu-latest, windowns-latest]
                node-version: [14, 16, 18]
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - run: node -v