name: Primeiro Fluxo
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Vitorino E."
            - name: Multiline Command
              run: |
                node -v
                npm -v
    parallel-job-linux:
        runs-on: ubuntu-latest
        steps:
            - name: View SO Version
              run: uname -a
    dependant-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-Output "Windows String Novo - Var"
            - name: Error Step
              run: doesnotexits

