name: Primeiro Fluxo
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Vitorino E."
            - name: Multiline Command
              run: |
                node -v
                npm -v