name: Workflow Run
on:
    workflow_run:
        workflows: [Repo Events]
        types: [completed]
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Eu fui acionado porque o Evento do repositório foi concluído!"